term xterm-256color
shell_integration enabled

allow_hyperlinks yes
detect_urls yes
open_url_with default

editor .
shell .

enable_audio_bell no
visual_bell_duration 0.3

click_interval -1.0

notify_on_cmd_finish unfocused 10 notify

clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask
clipboard_max_size 512
copy_on_select clipboard
paste_actions quote-urls-at-prompt,confirm
map ctrl+shift+c copy_to_clipboard
map cmd+c copy_to_clipboard 🍎
map ctrl+shift+v paste_from_clipboard
map cmd+v paste_from_clipboard 🍎
map ctrl+shift+o pass_selection_to_program


mouse_map left doublepress ungrabbed mouse_selection word
mouse_map left triplepress ungrabbed mouse_selection line
mouse_map middle release ungrabbed paste_from_selection
# active_border_color none
confirm_os_window_close 1
draw_minimal_borders yes
hide_window_decorations no
inactive_text_alpha 0.7
initial_window_height 400
initial_window_width 640
window_alert_on_bell yes
window_border_width 0.5pt
window_resize_step_cells 2
window_resize_step_lines 2
# default layout is vertical splits only
# enabled_layouts splits

bell_on_tab "🔔 "
map cmd+left previous_tab
map cmd+right next_tab
map cmd+t new_tab_with_cwd !neighbor


tab_bar_edge    top
tab_bar_margin_width    3
tab_bar_margin_height    5 5
tab_bar_style    fade
tab_fade    0
tab_title_template          "{fmt.bg._282a36}{fmt.fg._303030}{fmt.fg.default}{fmt.bg._303030}{fmt.fg._c6c6c6} {title} {fmt.fg.default}{fmt.bg.default}{fmt.fg._303030}{fmt.fg.default}"
active_tab_title_template   "{fmt.bg._282a36}{fmt.fg._ffb86c}{fmt.fg.default}{fmt.bg._ffb86c}{fmt.fg._080808} {title} {fmt.fg.default}{fmt.bg.default}{fmt.fg._ffb86c}{fmt.fg.default}"

# tab_bar_edge top
# tab_bar_min_tabs 2
# tab_title_template  " {index} {title} "
# tab_bar_style custom
# tab_powerline_style round


font_family FiraCode Nerd Font Mono Retina
font_size 13.0

macos_colorspace default
macos_option_as_alt no
macos_quit_when_last_window_closed yes
# macos_titlebar_color background
macos_thicken_font 0.75
macos_window_resizable yes
macos_titlebar_color background
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard

map cmd+w close_window
map cmd+shif+n new_os_window
map cmd+d launch - location=hsplit - cwd=current
map cmd+shift+d launch - location=vsplit - cwd=current

scrollback_lines 10000

mouse_hide_wait	-3.0

cursor_trail 200
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

allow_remote_control yes
listen_on unix:/tmp/mykitty

allow_remote_control_all yes

# https://github.com/trygveaa/kitty-kitten-search
# map cmd+f kitten search
map kitty_mod+/      launch --allow-remote-control kitty +kitten kitty_search/search.py @active-kitty-window-id

# BEGIN_KITTY_THEME
# Dracula
include current-theme.conf
# END_KITTY_THEME
#
