[tools]
elixir = "latest"
erlang = "latest"
java = "openjdk-25.0.0"
ruby = 'latest'
node = { version = "lts", postinstall = "corepack enable" }
zig = "latest"
python = "3"
lua = "latest"

[hooks]
enter = "echo 'I entered the project'"
leave = "echo 'I left the project'"
